# Scaling Up Alpha Zero General (Minichess)


## Topics Covered 

1. Initializing and displaying the Minichess Board
2. Checking whether game has ended or not
3. Defining players Player 1 and Player 2
4. Checking valid moves and mapping moves to Grid Points (to be enhanced to a3g5 format later)
5. Play all pieces one by one and validate (Pawn, Rook, King, Queen, Knight and Bishop)
6. Check Pawn cross attack
7. Check Pawn to reach last move and become Queuen
8. Complete the Game and check the winner



## Section 1 - Initializing and displaying the Minichess Board


- Load inital libraries

In [1]:
from Coach import Coach
from minichess.GardnerMiniChessGame import GardnerMiniChessGame as Game
from minichess.MiniChessLogic import Board
from minichess.keras.NNet import NNetWrapper as nn
from utils import *
import numpy as np

c:\users\karthik\appdata\local\programs\python\python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


- Load the Game and required Neural Network

In [2]:
g = Game()
nnet = nn(g)
board = g.getInitBoard()    
n = 5 # 5X5 Grid
logic = Board(n,board)
print(np.array(board))

[[  -479   -280   -320   -929 -60000]
 [  -100   -100   -100   -100   -100]
 [     0      0      0      0      0]
 [   100    100    100    100    100]
 [   479    280    320    929  60000]]


## Section 2 - Checking whether game has ended or not

- Verify the Canonical and User Board

In [3]:
player1 = 1
player2 = -1
g.display(board)

TypeError: display() missing 1 required positional argument: 'player'

- Check whether Game is ended
- It should return 0 since Game is still in Valid state

In [ ]:
print(g.getGameEnded(board,player1))

## Section 4 - Checking valid moves and mapping moves to Grid Points (to be enhanced to a3g5 format later)

- Check the next legal move we can do
- It Should list all Pawn moves for White and Horse moves

[(36, 29), (37, 30), (38, 31), (39, 32), (40, 33), (44, 29), (44, 31)]



Overal Chess Grid 5X5 Looks like this:

        # Chess GRID with Padding and Cell Number
        # [0,  1,  2,  3,  4,  5,  6]
        # [7,  8,  9,  10, 11, 12, 13]

        # [14,   15, 16, 17, 18, 19,     20]
        # [21,   22, 23, 24, 25, 26,     27]
        # [28,   29, 30, 31, 32, 33,     34]
        # [35,   36, 37, 38, 39, 40,     41]
        # [42,   43, 44, 45, 46, 47,     48]

        # [49, 50, 51, 52, 53, 54, 55]
        # [56, 57, 58, 59, 60, 61, 62]


In [ ]:
print('\nAll possible moves are: \n')
moves = []
for move in logic.get_legal_moves(player1):
    moves.append(move)
print(moves)
g.display(board)    

- Execute first move by moving the White Pawn from a2 to a3 

move = (36,29)

In [ ]:
logic.execute_move((36,29),player1)
g.display(logic.pieces_without_padding())

- Assign Player 2 as -1
- Get Legal moves for Player 2
- Execute one pawn Move

In [ ]:
player2 = -1
print('\nAll possible moves are: \n')
moves = []
for move in logic.get_legal_moves(player2):
    moves.append(move)
print(moves)
g.display(logic.pieces_without_padding())

## Section 4 - Checking valid moves and mapping moves to Grid Points (to be enhanced to a3g5 format later)

Overal Chess Grid 5X5 Looks like this:

        # Chess GRID with Padding and Cell Number
        # [0,  1,  2,  3,  4,  5,  6]
        # [7,  8,  9,  10, 11, 12, 13]

        # [14,   15, 16, 17, 18, 19,     20]
        # [21,   22, 23, 24, 25, 26,     27]
        # [28,   29, 30, 31, 32, 33,     34]
        # [35,   36, 37, 38, 39, 40,     41]
        # [42,   43, 44, 45, 46, 47,     48]

        # [49, 50, 51, 52, 53, 54, 55]
        # [56, 57, 58, 59, 60, 61, 62]
        
Now make a horse move from b1 to a3

In [ ]:
logic.execute_move((44,29),player2)
g.display(logic.pieces_without_padding())

- White to take the horse 
- List legal moves and take the horse 

In [ ]:
print('\nAll possible moves are: \n')
moves = []
for move in logic.get_legal_moves(player1):
    moves.append(move)
print(moves)
g.display(logic.pieces_without_padding())

In [ ]:
logic.execute_move((44,29),player1)
g.display(logic.pieces_without_padding())
print('\nAll possible moves are: \n')
moves = []
for move in logic.get_legal_moves(player2):
    moves.append(move)
print(moves)

## Section 5 - Play all pieces one by one and validate (Pawn, Rook, King, Queen, Knight and Bishop)

Refer the Grid to Make a move 


Overal Chess Grid 5X5 Looks like this:

        # Chess GRID with Padding and Cell Number
        # [0,  1,  2,  3,  4,  5,  6]
        # [7,  8,  9,  10, 11, 12, 13]

        # [14,   15, 16, 17, 18, 19,     20]
        # [21,   22, 23, 24, 25, 26,     27]
        # [28,   29, 30, 31, 32, 33,     34]
        # [35,   36, 37, 38, 39, 40,     41]
        # [42,   43, 44, 45, 46, 47,     48]

        # [49, 50, 51, 52, 53, 54, 55]
        # [56, 57, 58, 59, 60, 61, 62]
        


In [ ]:
logic.execute_move((37,29),player2)
g.display(logic.pieces_without_padding())
print('\nAll possible moves are: \n')
moves = []
for move in logic.get_legal_moves(player1):
    moves.append(move)
print(moves)

In [ ]:
logic.execute_move((43,29),player1)
g.display(logic.pieces_without_padding())
print('\nAll possible moves are: \n')
moves = []
for move in logic.get_legal_moves(player2):
    moves.append(move)
print(moves)

In [ ]:
logic.execute_move((45,29),player2)
g.display(logic.pieces_without_padding())

print('\nAll possible moves for Player 1 are: \n')
moves = []
for move in logic.get_legal_moves(player1):
    moves.append(move)
print(moves)

In [ ]:
logic.execute_move((37,29),player1)
g.display(logic.pieces_without_padding())

print('\nAll possible moves for Player 2 are: \n')
moves = []
for move in logic.get_legal_moves(player2):
    moves.append(move)
print(moves)

In [ ]:
logic.execute_move((46,44),player2)
g.display(logic.pieces_without_padding())

print('\nAll possible moves for Player 1 are: \n')
moves = []
for move in logic.get_legal_moves(player1):
    moves.append(move)
print(moves)

In [ ]:
logic.execute_move((39,32),player1)
g.display(logic.pieces_without_padding())

print('\nAll possible moves for Player 2 are: \n')
moves = []
for move in logic.get_legal_moves(player2):
    moves.append(move)
print(moves)

In [ ]:
logic.execute_move((44,37),player2)
g.display(logic.pieces_without_padding())

print('\nAll possible moves for Player 1 are: \n')
moves = []
for move in logic.get_legal_moves(player1):
    moves.append(move)
print(moves)

## Section 7 -  Check Pawn to reach last move and become Queuen


In [ ]:
logic.execute_move((32,24),player1)
g.display(logic.pieces_without_padding())

print('\nAll possible moves for Player 2 are: \n')
moves = []
for move in logic.get_legal_moves(player2):
    moves.append(move)
print(moves)

In [ ]:
logic.execute_move((37,25),player2)
g.display(logic.pieces_without_padding())

print('\nAll possible moves for Player 1 are: \n')
moves = []
for move in logic.get_legal_moves(player1):
    moves.append(move)
print(moves)

In [ ]:
logic.execute_move((24,17),player1)
g.display(logic.pieces_without_padding())

print('\nAll possible moves for Player 2 are: \n')
moves = []
for move in logic.get_legal_moves(player2):
    moves.append(move)
print(moves)

## Section 8 - Complete the Game and check the winner


In [ ]:
logic.execute_move((25,19),player2)
g.display(logic.pieces_without_padding())

print('\nAll possible moves for Player 1 are: \n')
moves = []
for move in logic.get_legal_moves(player1):
    moves.append(move)
print(moves)


In [ ]:
print(logic.is_win(player2))
print(logic.is_win(player1))
print(g.getGameEnded(logic.pieces_without_padding(),player2))

## Section 9 - Normalize Actions to Ids 

- Every piece can take any position in 5 X 5 Grid 
- Queen Can move diagonally and straig from every cell (0,0), (0,1) .... (3,1) ... (4,4) 
- Similarly every piece can move to all possible positions constrained by their rule
- We will store two hash maps 
- Action Identifier to Actions   { 51: ["Queen", "Cell 1", "Cell 10"], ... }
- Action to Action Identifier    { "Queen:Cell1:Cell10": 242, ... }

In [ ]:
print(g.id_to_action[100])
print(g.action_to_id["479:26:12"])

- Action size really huge compared to other board games because of different piece type and moves 
- This grows exponentially high once the board size starts growing (say n = 8)

In [ ]:
print(len(g.id_to_action))

## Section 10 - Get All Valid Moves in the MCTS consumable format

Overal Chess Grid 5X5 Looks like this:

        # Chess GRID with Padding and Cell Number
        # [0,  1,  2,  3,  4,  5,  6]
        # [7,  8,  9,  10, 11, 12, 13]

        # [14,   15, 16, 17, 18, 19,     20]
        # [21,   22, 23, 24, 25, 26,     27]
        # [28,   29, 30, 31, 32, 33,     34]
        # [35,   36, 37, 38, 39, 40,     41]
        # [42,   43, 44, 45, 46, 47,     48]

        # [49, 50, 51, 52, 53, 54, 55]
        # [56, 57, 58, 59, 60, 61, 62]
        

In [ ]:
import numpy as np
g = Game()
nnet = nn(g)
board = g.getInitBoard()    
n = 5 # 5X5 Grid
logic = Board(n,board)
print(np.array(board))
print('\nAll possible moves for Player 2 are: \n')
moves = []
for move in logic.get_legal_moves(player2):
    moves.append(move)
print(moves)
print(len(g.action_to_id))
valids = g.getValidMoves(board,player1)
print(len(valids))
count = 0
for i in valids:
    if i == 1: count += 1 
print(count)
print(len(moves))


## Section 11 - Train with MCTS 

- Changed Neural Network activation from softmax to sigmoid due to vanishing gradients
- Never use numpy array and python array mixed 
- Rotation and player switching in canonical board might be conufusing

In [4]:
from Coach import Coach
from minichess.GardnerMiniChessGame import GardnerMiniChessGame as Game
from minichess.keras.NNet import NNetWrapper as nn
from utils import *

args = dotdict({
    'numIters': 10,
    'numEps': 5,
    'tempThreshold': 15,
    'updateThreshold': 0.6,
    'maxlenOfQueue': 200,
    'arenaCompare': 10,
    'numMCTSSims': 25,
    'cpuct': 1,
    'checkpoint': './temp/',
    'load_model': False,
    'load_folder_file': ('/dev/models/8x100x50', 'best.pth.tar'),
    'numItersForTrainExamplesHistory': 20,
})

g = Game()
nnet = nn(g)
c = Coach(g, nnet, args)


In [ ]:
c.executeEpisode()
print()


♜ ♞ ♝ ♛ ♚
♟ ♟ ♟ ♟ ♟
·  ·  ·  ·  · 
♙ ♙ ♙ ♙ ♙
♖ ♘ ♗ ♕ ♔

♜ ♞ ♝ ♛ ♚
♟ ♟ ♟ ♟ ♟
♙ ·  ·  ·  · 
·  ♙ ♙ ♙ ♙
♖ ♘ ♗ ♕ ♔

♜ ·  ♝ ♛ ♚
♟ ♟ ♟ ♟ ♟
♙ ·  ♞ ·  · 
·  ♙ ♙ ♙ ♙
♖ ♘ ♗ ♕ ♔

♜ ·  ♝ ♛ ♚
♟ ♟ ♟ ♟ ♟
♙ ♙ ♞ ·  · 
·  ·  ♙ ♙ ♙
♖ ♘ ♗ ♕ ♔

♜ ·  ♝ ♛ ♚
♟ ♟ ♟ ♟ ♟
♙ ♙ ·  ·  · 
·  ·  ♙ ♙ ♞
♖ ♘ ♗ ♕ ♔
